"""changes

Revision ID: 90652f9b1ad7
Revises: 36f1598a52af
Create Date: 2023-09-15 14:39:13.210155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90652f9b1ad7'
down_revision = '36f1598a52af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_no', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reply_user_no_user'), 'user', ['user_no'], ['no'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reply_user_no_user'), type_='foreignkey')
        batch_op.drop_column('user_no')

    # ### end Alembic commands ###
